name: side_quest_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter  
  firebase_auth: ^5.7.0
  google_sign_in: ^6.1.1
  curved_navigation_bar: ^1.0.3
  location: ^5.0.1
  google_maps_flutter: ^2.7.0
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  firebase_core: ^3.8.0


flutter:
  uses-material-design: true
  assets:
  - lib/images/apple.png
  - lib/images/google.png